// ISO 4217 world currency list with country + flag (ISO-2) code for flagcdn.com
export type WorldCurrency = { code: string; name: string; country: string; cc: string };

export const WORLD_CURRENCIES: WorldCurrency[] = [
  { code: "AED", name: "UAE Dirham", country: "United Arab Emirates", cc: "ae" },
  { code: "AFN", name: "Afghan Afghani", country: "Afghanistan", cc: "af" },
  { code: "ALL", name: "Albanian Lek", country: "Albania", cc: "al" },
  { code: "AMD", name: "Armenian Dram", country: "Armenia", cc: "am" },
  { code: "ANG", name: "Netherlands Antillean Guilder", country: "Curaçao", cc: "cw" },
  { code: "AOA", name: "Angolan Kwanza", country: "Angola", cc: "ao" },
  { code: "ARS", name: "Argentine Peso", country: "Argentina", cc: "ar" },
  { code: "AUD", name: "Australian Dollar", country: "Australia", cc: "au" },
  { code: "AWG", name: "Aruban Florin", country: "Aruba", cc: "aw" },
  { code: "AZN", name: "Azerbaijani Manat", country: "Azerbaijan", cc: "az" },
  { code: "BAM", name: "Bosnia-Herzegovina Mark", country: "Bosnia & Herzegovina", cc: "ba" },
  { code: "BBD", name: "Barbadian Dollar", country: "Barbados", cc: "bb" },
  { code: "BDT", name: "Bangladeshi Taka", country: "Bangladesh", cc: "bd" },
  { code: "BGN", name: "Bulgarian Lev", country: "Bulgaria", cc: "bg" },
  { code: "BHD", name: "Bahraini Dinar", country: "Bahrain", cc: "bh" },
  { code: "BIF", name: "Burundian Franc", country: "Burundi", cc: "bi" },
  { code: "BMD", name: "Bermudan Dollar", country: "Bermuda", cc: "bm" },
  { code: "BND", name: "Brunei Dollar", country: "Brunei", cc: "bn" },
  { code: "BOB", name: "Bolivian Boliviano", country: "Bolivia", cc: "bo" },
  { code: "BRL", name: "Brazilian Real", country: "Brazil", cc: "br" },
  { code: "BSD", name: "Bahamian Dollar", country: "Bahamas", cc: "bs" },
  { code: "BTN", name: "Bhutanese Ngultrum", country: "Bhutan", cc: "bt" },
  { code: "BWP", name: "Botswanan Pula", country: "Botswana", cc: "bw" },
  { code: "BYN", name: "Belarusian Ruble", country: "Belarus", cc: "by" },
  { code: "BZD", name: "Belize Dollar", country: "Belize", cc: "bz" },
  { code: "CAD", name: "Canadian Dollar", country: "Canada", cc: "ca" },
  { code: "CDF", name: "Congolese Franc", country: "DR Congo", cc: "cd" },
  { code: "CHF", name: "Swiss Franc", country: "Switzerland", cc: "ch" },
  { code: "CLP", name: "Chilean Peso", country: "Chile", cc: "cl" },
  { code: "CNY", name: "Chinese Yuan", country: "China", cc: "cn" },
  { code: "COP", name: "Colombian Peso", country: "Colombia", cc: "co" },
  { code: "CRC", name: "Costa Rican Colón", country: "Costa Rica", cc: "cr" },
  { code: "CUP", name: "Cuban Peso", country: "Cuba", cc: "cu" },
  { code: "CVE", name: "Cape Verdean Escudo", country: "Cape Verde", cc: "cv" },
  { code: "CZK", name: "Czech Koruna", country: "Czechia", cc: "cz" },
  { code: "DJF", name: "Djiboutian Franc", country: "Djibouti", cc: "dj" },
  { code: "DKK", name: "Danish Krone", country: "Denmark", cc: "dk" },
  { code: "DOP", name: "Dominican Peso", country: "Dominican Republic", cc: "do" },
  { code: "DZD", name: "Algerian Dinar", country: "Algeria", cc: "dz" },
  { code: "EGP", name: "Egyptian Pound", country: "Egypt", cc: "eg" },
  { code: "ERN", name: "Eritrean Nakfa", country: "Eritrea", cc: "er" },
  { code: "ETB", name: "Ethiopian Birr", country: "Ethiopia", cc: "et" },
  { code: "EUR", name: "Euro", country: "European Union", cc: "eu" },
  { code: "FJD", name: "Fijian Dollar", country: "Fiji", cc: "fj" },
  { code: "FKP", name: "Falkland Islands Pound", country: "Falkland Islands", cc: "fk" },
  { code: "GBP", name: "British Pound", country: "United Kingdom", cc: "gb" },
  { code: "GEL", name: "Georgian Lari", country: "Georgia", cc: "ge" },
  { code: "GHS", name: "Ghanaian Cedi", country: "Ghana", cc: "gh" },
  { code: "GIP", name: "Gibraltar Pound", country: "Gibraltar", cc: "gi" },
  { code: "GMD", name: "Gambian Dalasi", country: "Gambia", cc: "gm" },
  { code: "GNF", name: "Guinean Franc", country: "Guinea", cc: "gn" },
  { code: "GTQ", name: "Guatemalan Quetzal", country: "Guatemala", cc: "gt" },
  { code: "GYD", name: "Guyanaese Dollar", country: "Guyana", cc: "gy" },
  { code: "HKD", name: "Hong Kong Dollar", country: "Hong Kong", cc: "hk" },
  { code: "HNL", name: "Honduran Lempira", country: "Honduras", cc: "hn" },
  { code: "HRK", name: "Croatian Kuna", country: "Croatia", cc: "hr" },
  { code: "HTG", name: "Haitian Gourde", country: "Haiti", cc: "ht" },
  { code: "HUF", name: "Hungarian Forint", country: "Hungary", cc: "hu" },
  { code: "IDR", name: "Indonesian Rupiah", country: "Indonesia", cc: "id" },
  { code: "ILS", name: "Israeli Shekel", country: "Israel", cc: "il" },
  { code: "INR", name: "Indian Rupee", country: "India", cc: "in" },
  { code: "IQD", name: "Iraqi Dinar", country: "Iraq", cc: "iq" },
  { code: "IRR", name: "Iranian Rial", country: "Iran", cc: "ir" },
  { code: "ISK", name: "Icelandic Króna", country: "Iceland", cc: "is" },
  { code: "JMD", name: "Jamaican Dollar", country: "Jamaica", cc: "jm" },
  { code: "JOD", name: "Jordanian Dinar", country: "Jordan", cc: "jo" },
  { code: "JPY", name: "Japanese Yen", country: "Japan", cc: "jp" },
  { code: "KES", name: "Kenyan Shilling", country: "Kenya", cc: "ke" },
  { code: "KGS", name: "Kyrgystani Som", country: "Kyrgyzstan", cc: "kg" },
  { code: "KHR", name: "Cambodian Riel", country: "Cambodia", cc: "kh" },
  { code: "KMF", name: "Comorian Franc", country: "Comoros", cc: "km" },
  { code: "KRW", name: "South Korean Won", country: "South Korea", cc: "kr" },
  { code: "KWD", name: "Kuwaiti Dinar", country: "Kuwait", cc: "kw" },
  { code: "KYD", name: "Cayman Islands Dollar", country: "Cayman Islands", cc: "ky" },
  { code: "KZT", name: "Kazakhstani Tenge", country: "Kazakhstan", cc: "kz" },
  { code: "LAK", name: "Laotian Kip", country: "Laos", cc: "la" },
  { code: "LBP", name: "Lebanese Pound", country: "Lebanon", cc: "lb" },
  { code: "LKR", name: "Sri Lankan Rupee", country: "Sri Lanka", cc: "lk" },
  { code: "LRD", name: "Liberian Dollar", country: "Liberia", cc: "lr" },
  { code: "LSL", name: "Lesotho Loti", country: "Lesotho", cc: "ls" },
  { code: "LYD", name: "Libyan Dinar", country: "Libya", cc: "ly" },
  { code: "MAD", name: "Moroccan Dirham", country: "Morocco", cc: "ma" },
  { code: "MDL", name: "Moldovan Leu", country: "Moldova", cc: "md" },
  { code: "MGA", name: "Malagasy Ariary", country: "Madagascar", cc: "mg" },
  { code: "MKD", name: "Macedonian Denar", country: "North Macedonia", cc: "mk" },
  { code: "MMK", name: "Myanma Kyat", country: "Myanmar", cc: "mm" },
  { code: "MNT", name: "Mongolian Tugrik", country: "Mongolia", cc: "mn" },
  { code: "MOP", name: "Macanese Pataca", country: "Macao", cc: "mo" },
  { code: "MRU", name: "Mauritanian Ouguiya", country: "Mauritania", cc: "mr" },
  { code: "MUR", name: "Mauritian Rupee", country: "Mauritius", cc: "mu" },
  { code: "MVR", name: "Maldivian Rufiyaa", country: "Maldives", cc: "mv" },
  { code: "MWK", name: "Malawian Kwacha", country: "Malawi", cc: "mw" },
  { code: "MXN", name: "Mexican Peso", country: "Mexico", cc: "mx" },
  { code: "MYR", name: "Malaysian Ringgit", country: "Malaysia", cc: "my" },
  { code: "MZN", name: "Mozambican Metical", country: "Mozambique", cc: "mz" },
  { code: "NAD", name: "Namibian Dollar", country: "Namibia", cc: "na" },
  { code: "NGN", name: "Nigerian Naira", country: "Nigeria", cc: "ng" },
  { code: "NIO", name: "Nicaraguan Córdoba", country: "Nicaragua", cc: "ni" },
  { code: "NOK", name: "Norwegian Krone", country: "Norway", cc: "no" },
  { code: "NPR", name: "Nepalese Rupee", country: "Nepal", cc: "np" },
  { code: "NZD", name: "New Zealand Dollar", country: "New Zealand", cc: "nz" },
  { code: "OMR", name: "Omani Rial", country: "Oman", cc: "om" },
  { code: "PAB", name: "Panamanian Balboa", country: "Panama", cc: "pa" },
  { code: "PEN", name: "Peruvian Sol", country: "Peru", cc: "pe" },
  { code: "PGK", name: "Papua New Guinean Kina", country: "Papua New Guinea", cc: "pg" },
  { code: "PHP", name: "Philippine Peso", country: "Philippines", cc: "ph" },
  { code: "PKR", name: "Pakistani Rupee", country: "Pakistan", cc: "pk" },
  { code: "PLN", name: "Polish Złoty", country: "Poland", cc: "pl" },
  { code: "PYG", name: "Paraguayan Guarani", country: "Paraguay", cc: "py" },
  { code: "QAR", name: "Qatari Rial", country: "Qatar", cc: "qa" },
  { code: "RON", name: "Romanian Leu", country: "Romania", cc: "ro" },
  { code: "RSD", name: "Serbian Dinar", country: "Serbia", cc: "rs" },
  { code: "RUB", name: "Russian Ruble", country: "Russia", cc: "ru" },
  { code: "RWF", name: "Rwandan Franc", country: "Rwanda", cc: "rw" },
  { code: "SAR", name: "Saudi Riyal", country: "Saudi Arabia", cc: "sa" },
  { code: "SBD", name: "Solomon Islands Dollar", country: "Solomon Islands", cc: "sb" },
  { code: "SCR", name: "Seychellois Rupee", country: "Seychelles", cc: "sc" },
  { code: "SDG", name: "Sudanese Pound", country: "Sudan", cc: "sd" },
  { code: "SEK", name: "Swedish Krona", country: "Sweden", cc: "se" },
  { code: "SGD", name: "Singapore Dollar", country: "Singapore", cc: "sg" },
  { code: "SHP", name: "St. Helena Pound", country: "St. Helena", cc: "sh" },
  { code: "SLE", name: "Sierra Leonean Leone", country: "Sierra Leone", cc: "sl" },
  { code: "SOS", name: "Somali Shilling", country: "Somalia", cc: "so" },
  { code: "SRD", name: "Surinamese Dollar", country: "Suriname", cc: "sr" },
  { code: "SSP", name: "South Sudanese Pound", country: "South Sudan", cc: "ss" },
  { code: "STN", name: "São Tomé & Príncipe Dobra", country: "São Tomé & Príncipe", cc: "st" },
  { code: "SVC", name: "Salvadoran Colón", country: "El Salvador", cc: "sv" },
  { code: "SYP", name: "Syrian Pound", country: "Syria", cc: "sy" },
  { code: "SZL", name: "Swazi Lilangeni", country: "Eswatini", cc: "sz" },
  { code: "THB", name: "Thai Baht", country: "Thailand", cc: "th" },
  { code: "TJS", name: "Tajikistani Somoni", country: "Tajikistan", cc: "tj" },
  { code: "TMT", name: "Turkmenistani Manat", country: "Turkmenistan", cc: "tm" },
  { code: "TND", name: "Tunisian Dinar", country: "Tunisia", cc: "tn" },
  { code: "TOP", name: "Tongan Paʻanga", country: "Tonga", cc: "to" },
  { code: "TRY", name: "Turkish Lira", country: "Turkey", cc: "tr" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", country: "Trinidad & Tobago", cc: "tt" },
  { code: "TWD", name: "New Taiwan Dollar", country: "Taiwan", cc: "tw" },
  { code: "TZS", name: "Tanzanian Shilling", country: "Tanzania", cc: "tz" },
  { code: "UAH", name: "Ukrainian Hryvnia", country: "Ukraine", cc: "ua" },
  { code: "UGX", name: "Ugandan Shilling", country: "Uganda", cc: "ug" },
  { code: "USD", name: "US Dollar", country: "United States", cc: "us" },
  { code: "UYU", name: "Uruguayan Peso", country: "Uruguay", cc: "uy" },
  { code: "UZS", name: "Uzbekistan Som", country: "Uzbekistan", cc: "uz" },
  { code: "VES", name: "Venezuelan Bolívar", country: "Venezuela", cc: "ve" },
  { code: "VND", name: "Vietnamese Dong", country: "Vietnam", cc: "vn" },
  { code: "VUV", name: "Vanuatu Vatu", country: "Vanuatu", cc: "vu" },
  { code: "WST", name: "Samoan Tala", country: "Samoa", cc: "ws" },
  { code: "XAF", name: "Central African CFA Franc", country: "Central Africa", cc: "cm" },
  { code: "XCD", name: "East Caribbean Dollar", country: "East Caribbean", cc: "ag" },
  { code: "XOF", name: "West African CFA Franc", country: "West Africa", cc: "sn" },
  { code: "XPF", name: "CFP Franc", country: "French Polynesia", cc: "pf" },
  { code: "YER", name: "Yemeni Rial", country: "Yemen", cc: "ye" },
  { code: "ZAR", name: "South African Rand", country: "South Africa", cc: "za" },
  { code: "ZMW", name: "Zambian Kwacha", country: "Zambia", cc: "zm" },
  { code: "ZWL", name: "Zimbabwean Dollar", country: "Zimbabwe", cc: "zw" },
];

export const WORLD_CURRENCY_MAP: Record<string, WorldCurrency> = Object.fromEntries(
  WORLD_CURRENCIES.map((c) => [c.code, c]),
);
