project_id = "hgmskcvaeadnyovbroup"

[functions.refresh-fx-rates]
verify_jwt = false

[functions.flutterwave-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.paysafe-webhook]
verify_jwt = false

[functions.paysafe-payout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-payout]
verify_jwt = false

[functions.stripe-payout-webhook]
verify_jwt = false

[functions.elicate-webhook]
verify_jwt = false

[functions.elicate-payout]
verify_jwt = false

[functions.mtn-momo-payout]
verify_jwt = false

[functions.mtn-momo-webhook]
verify_jwt = false

[functions.test-integrations]
verify_jwt = false

[functions.stripe-issuing-webhook]
verify_jwt = false

[functions.pawapay-webhook]
verify_jwt = false

[functions.interac-callback]
verify_jwt = false


