import type {
  CorridorRateCard,
  CostComponents,
  PayoutMethod,
  PayoutMinimum,
  VolumeDiscountTier,
} from "./types.ts";

/** Starting commercial rates — not hard-coded economics. Effective 2026-09-10. */
export const RATE_CARD_EFFECTIVE_FROM = "2026-09-10";

export const DEFAULT_TRANSFER_FEE_PCT = 0.005;

export const DEFAULT_WALLET_COSTS: CostComponents = {
  partner_cost_pct: 0,
  partner_fixed_fee: 0,
  payment_cost_pct: 0,
  payment_fixed_fee: 0.05,
  payout_cost_fixed: 0,
  liquidity_cost_pct: 0.0005,
  risk_cost_pct: 0.0003,
  required_margin: 0.15,
};

export const DEFAULT_EXTERNAL_COSTS: CostComponents = {
  partner_cost_pct: 0.006,
  partner_fixed_fee: 0.75,
  payment_cost_pct: 0.005,
  payment_fixed_fee: 0.25,
  payout_cost_fixed: 0,
  liquidity_cost_pct: 0.0015,
  risk_cost_pct: 0.001,
  required_margin: 0.75,
};

const costs = (overrides: Partial<CostComponents>, base: CostComponents = DEFAULT_EXTERNAL_COSTS): CostComponents => ({
  ...base,
  ...overrides,
});

const row = (
  partial: Omit<CorridorRateCard, "volume_discount" | "effective_from" | "effective_to" | "active" | "efin_transfer_fee_pct"> & {
    efin_transfer_fee_pct?: number;
  },
): CorridorRateCard => ({
  efin_transfer_fee_pct: DEFAULT_TRANSFER_FEE_PCT,
  volume_discount: 0,
  effective_from: RATE_CARD_EFFECTIVE_FROM,
  effective_to: null,
  active: true,
  ...partial,
});

/** Layer 1+2 starting card for CAD-funded external remittance. */
export const CUSTOMER_CORRIDOR_RATES: CorridorRateCard[] = [
  row({
    corridor_id: "CAD_USD_BANK",
    source_currency: "CAD",
    destination_currency: "USD",
    payout_method: "BANK",
    channel: "external",
    delivery: "Bank",
    partner: null,
    efin_fx_spread: 0.005,
    transfer_fee: 1.5,
    minimum_fee: 1.5,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Highly competitive",
    estimated_delivery: "1–2 business days",
    costs: costs({
      partner_cost_pct: 0.0015,
      partner_fixed_fee: 0.35,
      payment_cost_pct: 0.0025,
      payment_fixed_fee: 0.15,
      liquidity_cost_pct: 0.0008,
      risk_cost_pct: 0.0004,
      required_margin: 0.5,
    }),
  }),
  row({
    corridor_id: "CAD_USD_WALLET",
    source_currency: "CAD",
    destination_currency: "USD",
    payout_method: "WALLET",
    channel: "external",
    delivery: "Wallet",
    partner: null,
    efin_fx_spread: 0.006,
    transfer_fee: 1.5,
    minimum_fee: 1.5,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "Minutes",
    costs: costs({
      partner_cost_pct: 0.002,
      partner_fixed_fee: 0.25,
      payment_cost_pct: 0.0025,
      payment_fixed_fee: 0.15,
      required_margin: 0.5,
    }),
  }),
  row({
    corridor_id: "CAD_ZMW_MOBILE_MONEY",
    source_currency: "CAD",
    destination_currency: "ZMW",
    payout_method: "MOBILE_MONEY",
    channel: "external",
    delivery: "Mobile Money",
    partner: "PawaPay",
    efin_fx_spread: 0.015,
    transfer_fee: 3.49,
    minimum_fee: 3.49,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "Minutes",
    costs: costs({
      partner_cost_pct: 0.005,
      partner_fixed_fee: 0.75,
      payment_cost_pct: 0.005,
      payment_fixed_fee: 0.25,
      liquidity_cost_pct: 0.002,
      risk_cost_pct: 0.001,
      required_margin: 0.75,
    }),
  }),
  row({
    corridor_id: "CAD_ZMW_BANK",
    source_currency: "CAD",
    destination_currency: "ZMW",
    payout_method: "BANK",
    channel: "external",
    delivery: "Bank",
    partner: "PawaPay",
    efin_fx_spread: 0.0125,
    transfer_fee: 2.99,
    minimum_fee: 2.99,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "Same day – 1 business day",
    costs: costs({ partner_cost_pct: 0.0045, partner_fixed_fee: 0.65, required_margin: 0.75 }),
  }),
  row({
    corridor_id: "CAD_NGN_BANK",
    source_currency: "CAD",
    destination_currency: "NGN",
    payout_method: "BANK",
    channel: "external",
    delivery: "Bank",
    partner: "Nomba",
    efin_fx_spread: 0.015,
    transfer_fee: 3.49,
    minimum_fee: 3.49,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "Minutes – 1 hour",
    costs: costs({ partner_cost_pct: 0.0055, partner_fixed_fee: 0.6 }),
  }),
  row({
    corridor_id: "CAD_NGN_WALLET",
    source_currency: "CAD",
    destination_currency: "NGN",
    payout_method: "WALLET",
    channel: "external",
    delivery: "Wallet",
    partner: "Nomba",
    efin_fx_spread: 0.0175,
    transfer_fee: 3.99,
    minimum_fee: 3.99,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "Minutes",
    costs: costs({ partner_cost_pct: 0.006, partner_fixed_fee: 0.7 }),
  }),
  row({
    corridor_id: "CAD_KES_MOBILE_MONEY",
    source_currency: "CAD",
    destination_currency: "KES",
    payout_method: "MOBILE_MONEY",
    channel: "external",
    delivery: "Mobile Money",
    partner: "PawaPay",
    efin_fx_spread: 0.015,
    transfer_fee: 3.49,
    minimum_fee: 3.49,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "Minutes",
    costs: costs({ partner_cost_pct: 0.005, partner_fixed_fee: 0.7 }),
  }),
  row({
    corridor_id: "CAD_KES_BANK",
    source_currency: "CAD",
    destination_currency: "KES",
    payout_method: "BANK",
    channel: "external",
    delivery: "Bank",
    partner: "PawaPay",
    efin_fx_spread: 0.0125,
    transfer_fee: 2.99,
    minimum_fee: 2.99,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "Same day – 1 business day",
    costs: costs({ partner_cost_pct: 0.0045, partner_fixed_fee: 0.6 }),
  }),
  row({
    corridor_id: "CAD_ZAR_BANK",
    source_currency: "CAD",
    destination_currency: "ZAR",
    payout_method: "BANK",
    channel: "external",
    delivery: "Bank",
    partner: null,
    efin_fx_spread: 0.01,
    transfer_fee: 2.49,
    minimum_fee: 2.49,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "1–2 business days",
    costs: costs({ partner_cost_pct: 0.0035, partner_fixed_fee: 0.55, required_margin: 0.6 }),
  }),
  row({
    corridor_id: "CAD_ZAR_WALLET",
    source_currency: "CAD",
    destination_currency: "ZAR",
    payout_method: "WALLET",
    channel: "external",
    delivery: "Wallet",
    partner: null,
    efin_fx_spread: 0.0125,
    transfer_fee: 2.99,
    minimum_fee: 2.99,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "Minutes",
    costs: costs({ partner_cost_pct: 0.004, partner_fixed_fee: 0.5, required_margin: 0.6 }),
  }),
  row({
    corridor_id: "CAD_ZWG_WALLET_BANK",
    source_currency: "CAD",
    destination_currency: "ZWG",
    payout_method: "WALLET_BANK",
    channel: "external",
    delivery: "Wallet/Bank",
    partner: null,
    efin_fx_spread: 0.02,
    transfer_fee: 4.49,
    minimum_fee: 4.49,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Higher-risk corridor",
    estimated_delivery: "Same day – 2 business days",
    costs: costs({
      partner_cost_pct: 0.008,
      partner_fixed_fee: 1.1,
      liquidity_cost_pct: 0.003,
      risk_cost_pct: 0.004,
      required_margin: 1.0,
    }),
  }),
  row({
    corridor_id: "CAD_UGX_MOBILE_MONEY",
    source_currency: "CAD",
    destination_currency: "UGX",
    payout_method: "MOBILE_MONEY",
    channel: "external",
    delivery: "Mobile Money",
    partner: "PawaPay",
    efin_fx_spread: 0.0175,
    transfer_fee: 3.99,
    minimum_fee: 3.99,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "Minutes",
    costs: costs({ partner_cost_pct: 0.006, partner_fixed_fee: 0.8 }),
  }),
  row({
    corridor_id: "CAD_TZS_MOBILE_MONEY",
    source_currency: "CAD",
    destination_currency: "TZS",
    payout_method: "MOBILE_MONEY",
    channel: "external",
    delivery: "Mobile Money",
    partner: "PawaPay",
    efin_fx_spread: 0.0175,
    transfer_fee: 3.99,
    minimum_fee: 3.99,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "Minutes",
    costs: costs({ partner_cost_pct: 0.006, partner_fixed_fee: 0.8 }),
  }),
  row({
    corridor_id: "CAD_BIF_MOBILE_MONEY_BANK",
    source_currency: "CAD",
    destination_currency: "BIF",
    payout_method: "WALLET_BANK",
    channel: "external",
    delivery: "Mobile Money/Bank",
    partner: null,
    efin_fx_spread: 0.02,
    transfer_fee: 4.49,
    minimum_fee: 4.49,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Higher-cost corridor",
    estimated_delivery: "Same day – 2 business days",
    costs: costs({
      partner_cost_pct: 0.008,
      partner_fixed_fee: 1.0,
      liquidity_cost_pct: 0.0025,
      risk_cost_pct: 0.003,
      required_margin: 1.0,
    }),
  }),
  row({
    corridor_id: "CAD_GHS_MOBILE_MONEY",
    source_currency: "CAD",
    destination_currency: "GHS",
    payout_method: "MOBILE_MONEY",
    channel: "external",
    delivery: "Mobile Money",
    partner: "PawaPay",
    efin_fx_spread: 0.0175,
    transfer_fee: 3.99,
    minimum_fee: 3.99,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Competitive",
    estimated_delivery: "Minutes",
    costs: costs({ partner_cost_pct: 0.006, partner_fixed_fee: 0.75 }),
  }),
  row({
    corridor_id: "CAD_CDF_MOBILE_MONEY_BANK",
    source_currency: "CAD",
    destination_currency: "CDF",
    payout_method: "WALLET_BANK",
    channel: "external",
    delivery: "Mobile Money/Bank",
    partner: null,
    efin_fx_spread: 0.02,
    transfer_fee: 4.49,
    minimum_fee: 4.49,
    maximum_fee: 50,
    fee_currency: "CAD",
    recommended_position: "Higher-cost corridor",
    estimated_delivery: "Same day – 2 business days",
    costs: costs({
      partner_cost_pct: 0.008,
      partner_fixed_fee: 1.0,
      liquidity_cost_pct: 0.0025,
      risk_cost_pct: 0.003,
      required_margin: 1.0,
    }),
  }),
];

/** Internal wallet-to-wallet — priced below external remittance. */
export const WALLET_RATES: CorridorRateCard[] = [
  row({
    corridor_id: "WALLET_SAME_CURRENCY",
    source_currency: "*",
    destination_currency: "*",
    payout_method: "WALLET_TO_WALLET",
    channel: "wallet",
    delivery: "eFinMoney wallet",
    partner: "eFinMoney",
    efin_fx_spread: 0,
    efin_transfer_fee_pct: 0,
    transfer_fee: 0.5,
    minimum_fee: 0.5,
    maximum_fee: 25,
    fee_currency: "CAD",
    recommended_position: "Ecosystem",
    estimated_delivery: "Instant",
    costs: DEFAULT_WALLET_COSTS,
  }),
  row({
    corridor_id: "WALLET_CAD_USD",
    source_currency: "CAD",
    destination_currency: "USD",
    payout_method: "WALLET_TO_WALLET",
    channel: "wallet",
    delivery: "eFinMoney wallet",
    partner: "eFinMoney",
    efin_fx_spread: 0.005,
    transfer_fee: 0.5,
    minimum_fee: 0.5,
    maximum_fee: 25,
    fee_currency: "CAD",
    recommended_position: "Ecosystem",
    estimated_delivery: "Instant",
    costs: DEFAULT_WALLET_COSTS,
  }),
  row({
    corridor_id: "WALLET_CAD_USDC",
    source_currency: "CAD",
    destination_currency: "USDC",
    payout_method: "WALLET_TO_WALLET",
    channel: "wallet",
    delivery: "eFinMoney wallet",
    partner: "eFinMoney",
    efin_fx_spread: 0.005,
    transfer_fee: 0.5,
    minimum_fee: 0.5,
    maximum_fee: 25,
    fee_currency: "CAD",
    recommended_position: "Ecosystem",
    estimated_delivery: "Instant",
    costs: DEFAULT_WALLET_COSTS,
  }),
  row({
    corridor_id: "WALLET_USD_USDC",
    source_currency: "USD",
    destination_currency: "USDC",
    payout_method: "WALLET_TO_WALLET",
    channel: "wallet",
    delivery: "eFinMoney wallet",
    partner: "eFinMoney",
    efin_fx_spread: 0.005,
    transfer_fee: 0.5,
    minimum_fee: 0.5,
    maximum_fee: 25,
    fee_currency: "USD",
    recommended_position: "Ecosystem",
    estimated_delivery: "Instant",
    costs: { ...DEFAULT_WALLET_COSTS, required_margin: 0.12 },
  }),
  row({
    corridor_id: "WALLET_CAD_ZMW",
    source_currency: "CAD",
    destination_currency: "ZMW",
    payout_method: "WALLET_TO_WALLET",
    channel: "wallet",
    delivery: "eFinMoney wallet",
    partner: "eFinMoney",
    efin_fx_spread: 0.0125,
    transfer_fee: 1.5,
    minimum_fee: 1.5,
    maximum_fee: 25,
    fee_currency: "CAD",
    recommended_position: "Ecosystem",
    estimated_delivery: "Instant",
    costs: { ...DEFAULT_WALLET_COSTS, liquidity_cost_pct: 0.001, risk_cost_pct: 0.0008, required_margin: 0.35 },
  }),
  row({
    corridor_id: "WALLET_CAD_NGN",
    source_currency: "CAD",
    destination_currency: "NGN",
    payout_method: "WALLET_TO_WALLET",
    channel: "wallet",
    delivery: "eFinMoney wallet",
    partner: "eFinMoney",
    efin_fx_spread: 0.015,
    transfer_fee: 1.5,
    minimum_fee: 1.5,
    maximum_fee: 25,
    fee_currency: "CAD",
    recommended_position: "Ecosystem",
    estimated_delivery: "Instant",
    costs: { ...DEFAULT_WALLET_COSTS, liquidity_cost_pct: 0.001, risk_cost_pct: 0.0008, required_margin: 0.35 },
  }),
  row({
    corridor_id: "WALLET_CAD_KES",
    source_currency: "CAD",
    destination_currency: "KES",
    payout_method: "WALLET_TO_WALLET",
    channel: "wallet",
    delivery: "eFinMoney wallet",
    partner: "eFinMoney",
    efin_fx_spread: 0.0125,
    transfer_fee: 1.5,
    minimum_fee: 1.5,
    maximum_fee: 25,
    fee_currency: "CAD",
    recommended_position: "Ecosystem",
    estimated_delivery: "Instant",
    costs: { ...DEFAULT_WALLET_COSTS, liquidity_cost_pct: 0.001, risk_cost_pct: 0.0008, required_margin: 0.35 },
  }),
  row({
    corridor_id: "WALLET_CAD_ZAR",
    source_currency: "CAD",
    destination_currency: "ZAR",
    payout_method: "WALLET_TO_WALLET",
    channel: "wallet",
    delivery: "eFinMoney wallet",
    partner: "eFinMoney",
    efin_fx_spread: 0.01,
    transfer_fee: 1.5,
    minimum_fee: 1.5,
    maximum_fee: 25,
    fee_currency: "CAD",
    recommended_position: "Ecosystem",
    estimated_delivery: "Instant",
    costs: { ...DEFAULT_WALLET_COSTS, liquidity_cost_pct: 0.001, risk_cost_pct: 0.0006, required_margin: 0.3 },
  }),
];

export const VOLUME_DISCOUNT_TIERS: VolumeDiscountTier[] = [
  { id: "v0", min_monthly_volume: 0, max_monthly_volume: 999.99, fx_spread_discount: 0, transfer_fee_discount: 0, label: "Standard", custom: false },
  { id: "v1k", min_monthly_volume: 1000, max_monthly_volume: 4999.99, fx_spread_discount: 0.05, transfer_fee_discount: 0.05, label: "C$1,000 – C$4,999", custom: false },
  { id: "v5k", min_monthly_volume: 5000, max_monthly_volume: 9999.99, fx_spread_discount: 0.1, transfer_fee_discount: 0.1, label: "C$5,000 – C$9,999", custom: false },
  { id: "v10k", min_monthly_volume: 10000, max_monthly_volume: 24999.99, fx_spread_discount: 0.15, transfer_fee_discount: 0.15, label: "C$10,000 – C$24,999", custom: false },
  { id: "v25k", min_monthly_volume: 25000, max_monthly_volume: 49999.99, fx_spread_discount: 0.2, transfer_fee_discount: 0.2, label: "C$25,000 – C$49,999", custom: false },
  { id: "v50k", min_monthly_volume: 50000, max_monthly_volume: 99999.99, fx_spread_discount: 0.25, transfer_fee_discount: 0.25, label: "C$50,000 – C$99,999", custom: false },
  { id: "v100k", min_monthly_volume: 100000, max_monthly_volume: null, fx_spread_discount: 0.25, transfer_fee_discount: 0.25, label: "C$100,000+", custom: true },
];

export const PAYOUT_MINIMUMS: PayoutMinimum[] = [
  { payout_method: "WALLET_TO_WALLET", label: "eFinMoney wallet-to-wallet", minimum_fee: 0.5, fee_currency: "CAD" },
  { payout_method: "BANK", label: "Bank transfer", minimum_fee: 1.5, fee_currency: "CAD" },
  { payout_method: "MOBILE_MONEY", label: "Mobile Money", minimum_fee: 3.49, fee_currency: "CAD" },
  { payout_method: "CASH_PICKUP", label: "Cash pickup", minimum_fee: 4.99, fee_currency: "CAD" },
  { payout_method: "CARD_PAYOUT", label: "Card payout", minimum_fee: 4.99, fee_currency: "CAD" },
  { payout_method: "STABLECOIN", label: "Stablecoin", minimum_fee: 1.5, fee_currency: "CAD" },
  { payout_method: "CORPORATE", label: "Corporate payout", minimum_fee: 5.0, fee_currency: "CAD" },
  { payout_method: "WALLET", label: "External wallet", minimum_fee: 1.5, fee_currency: "CAD" },
];

export const ADMIN_CONFIGURATION_FIELDS: Array<{ field: string; example: string; notes: string }> = [
  { field: "corridor_id", example: "CAD_ZMW", notes: "Stable key for the corridor + payout method" },
  { field: "source_currency", example: "CAD", notes: "ISO-4217 (USDC treated as USD-pegged)" },
  { field: "destination_currency", example: "ZMW", notes: "ISO-4217 or stablecoin ticker" },
  { field: "payout_method", example: "MOBILE_MONEY", notes: "Wallet, bank, mobile money, cash, card, stablecoin, corporate" },
  { field: "partner", example: "PawaPay", notes: "Contracted carrier; costs come from the partner rate sheet" },
  { field: "partner_cost_pct", example: "0.60%", notes: "Layer 1 — carrier variable cost" },
  { field: "partner_fixed_fee", example: "C$0.75", notes: "Layer 1 — carrier fixed cost" },
  { field: "payment_cost_pct", example: "0.50%", notes: "Layer 1 — collection / processing" },
  { field: "payment_fixed_fee", example: "C$0.25", notes: "Layer 1 — collection fixed cost" },
  { field: "liquidity_cost_pct", example: "0.15%", notes: "Layer 1 — float / pre-funding" },
  { field: "risk_cost_pct", example: "0.10%", notes: "Layer 1 — compliance / risk allocation" },
  { field: "efin_fx_spread", example: "1.50%", notes: "Layer 2 — applied to mid-market: CUSTOMER_RATE = MID × (1 − spread)" },
  { field: "efin_transfer_fee_pct", example: "0.50%", notes: "Layer 2 — variable transfer fee" },
  { field: "minimum_fee", example: "C$3.49", notes: "Layer 2 — never charge less than this unless a promo row says otherwise" },
  { field: "maximum_fee", example: "C$50.00", notes: "Layer 2 — optional cap" },
  { field: "volume_discount", example: "0%", notes: "Layer 3 — resolved from monthly volume, not stored as a constant" },
  { field: "effective_from", example: "2026-09-10", notes: "Versioned commercial rate" },
  { field: "effective_to", example: "NULL", notes: "NULL = current" },
  { field: "active", example: "TRUE", notes: "Soft-retire instead of deleting history" },
];

export const PRICING_LAYERS = [
  {
    layer: "Layer 1 — Cost",
    items: ["Partner / carrier cost", "Payment processing cost", "Payout cost", "Liquidity cost", "FX hedge / volatility cost", "Compliance / risk allocation"],
  },
  {
    layer: "Layer 2 — eFinMoney pricing",
    items: ["FX spread", "Transfer fee", "Minimum fee", "Maximum fee", "Volume discount", "Cost-recovery floor"],
  },
  {
    layer: "Layer 3 — Customer segment",
    items: ["Consumer", "Business (negotiated FX spreads)", "Enterprise", "Partner / API", "High-volume"],
  },
];

export const STABLECOIN_PEGS: Record<string, string> = {
  USDC: "USD",
  USDT: "USD",
};

export function normalizeCurrency(code: string | null | undefined): string {
  return String(code || "").trim().toUpperCase();
}

export function payoutMethodFromInput(raw: string | null | undefined, channel: "wallet" | "external"): PayoutMethod {
  const v = String(raw || "").trim().toUpperCase().replace(/[\s-]+/g, "_");
  if (channel === "wallet" || v === "FX_SWAP" || v === "WALLET_TO_WALLET") return "WALLET_TO_WALLET";
  if (v === "MOBILE_MONEY" || v === "MOMO" || v === "MOBILE") return "MOBILE_MONEY";
  if (v === "BANK" || v === "BANK_TRANSFER" || v === "EFT") return "BANK";
  if (v === "CASH" || v === "CASH_PICKUP") return "CASH_PICKUP";
  if (v === "CARD" || v === "CARD_PAYOUT" || v === "CARD_PUSH") return "CARD_PAYOUT";
  if (v === "STABLECOIN" || v === "USDC" || v === "USDT") return "STABLECOIN";
  if (v === "CORPORATE" || v === "B2B") return "CORPORATE";
  if (v === "WALLET_BANK" || v === "WALLET/BANK" || v === "MOBILE_MONEY/BANK") return "WALLET_BANK";
  if (v === "WALLET") return "WALLET";
  return channel === "external" ? "BANK" : "WALLET_TO_WALLET";
}

export function allStartingRateCards(): CorridorRateCard[] {
  return [...WALLET_RATES, ...CUSTOMER_CORRIDOR_RATES];
}
