import { useState, useEffect, createContext, useContext, ReactNode } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { User, Session } from '@supabase/supabase-js';
import { identifyUser, resetAnalytics, track } from '@/lib/analytics';

interface AuthContextType {
  user: User | null;
  session: Session | null;
  loading: boolean;
  signUp: (email: string, password: string, fullName: string) => Promise<{ error: Error | null }>;
  signIn: (email: string, password: string) => Promise<{ error: Error | null }>;
  signOut: () => Promise<void>;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export const AuthProvider = ({ children }: { children: ReactNode }) => {
  const [user, setUser] = useState<User | null>(null);
  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let settled = false;
    // Clear the loading gate exactly once, no matter which path resolves first.
    const stopLoading = () => { if (!settled) { settled = true; setLoading(false); } };

    // Set up auth state listener FIRST
    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      async (event, session) => {
        setSession(session);
        setUser(session?.user ?? null);
        stopLoading();
        if (session?.user) {
          identifyUser(session.user.id, { email: session.user.email });
        } else if (event === 'SIGNED_OUT') {
          resetAnalytics();
        }
      }
    );

    // THEN check for existing session. Guard against a rejected/hanging
    // getSession() (e.g. a stale token) trapping the app on the spinner.
    supabase.auth.getSession()
      .then(({ data: { session } }) => {
        setSession(session);
        setUser(session?.user ?? null);
      })
      .catch((e) => console.warn('getSession failed', e))
      .finally(stopLoading);

    // Safety net: never leave the user stuck on the loading spinner if auth
    // initialization stalls for any reason.
    const timeout = window.setTimeout(stopLoading, 8000);

    return () => {
      subscription.unsubscribe();
      window.clearTimeout(timeout);
    };
  }, []);

  const signUp = async (email: string, password: string, fullName: string) => {
    try {
      const { error } = await supabase.auth.signUp({
        email,
        password,
        options: {
          emailRedirectTo: window.location.origin,
          data: {
            full_name: fullName,
          },
        },
      });
      
      if (error) throw error;

      // Update profile with full name after signup
      if (!error) {
        const { data: { user } } = await supabase.auth.getUser();
        if (user) {
          track('user_signed_up', { email });
          await supabase
            .from('profiles')
            .update({ full_name: fullName })
            .eq('user_id', user.id);

          // Fetch profile (account_number is generated by DB trigger).
          // Retry briefly in case the trigger hasn't completed yet.
          let accountNumber: string | null = null;
          let efinTag: string | null = null;
          for (let i = 0; i < 5; i++) {
            const { data: p } = await supabase
              .from('profiles')
              .select('account_number, efin_tag')
              .eq('user_id', user.id)
              .maybeSingle();
            if (p?.account_number) {
              accountNumber = p.account_number as string;
              efinTag = (p.efin_tag as string | null) ?? null;
              break;
            }
            await new Promise((r) => setTimeout(r, 400));
          }

          // Fire-and-forget welcome email with account number + @efin tag invite
          supabase.functions.invoke('send-email', {
            body: {
              type: 'welcome',
              to: email,
              data: {
                name: fullName,
                account_number: accountNumber,
                efin_tag: efinTag,
                app_url: window.location.origin,
              },
            },
          }).catch((e) => console.warn('welcome email failed', e));
        }
      }

      return { error: null };
    } catch (error) {
      return { error: error as Error };
    }
  };

  const signIn = async (email: string, password: string) => {
    try {
      const { error } = await supabase.auth.signInWithPassword({
        email,
        password,
      });
      if (error) throw error;
      return { error: null };
    } catch (error) {
      return { error: error as Error };
    }
  };

  const signOut = async () => {
    try {
      await supabase.auth.signOut({ scope: 'local' });
    } catch (e) {
      console.warn('signOut error, forcing local clear', e);
    }
    try {
      Object.keys(localStorage)
        .filter((k) => k.startsWith('sb-') && k.endsWith('-auth-token'))
        .forEach((k) => localStorage.removeItem(k));
    } catch {}
    setSession(null);
    setUser(null);
    window.location.assign('/auth');
  };

  return (
    <AuthContext.Provider value={{ user, session, loading, signUp, signIn, signOut }}>
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};
