/** Local EN/FR strings + Canadian lookups for the Interac checkout only. */

import { FINCRA_CAD_INTERAC_ALIAS } from "@/lib/fincraCad";

export type Lang = "en" | "fr";

export const CHECKOUT_STRINGS = {
  en: {
    selectMethod: "Select a payment method",
    interac: "Interac",
    interacDesc: "Use your bank account to approve an instant Interac payment",
    plaid: "Bank EFT",
    plaidDesc: "Pay by EFT from your linked Canadian bank to Loop Bank",
    loopBilling: "Loop payment link",
    loopBillingDesc: "Pay via Loop Billing (EFT bank debit · ~4 business days)",
    card: "Card",
    cardDesc: "Use debit or credit card to make instant payments",
    visaDirect: "Visa Direct",
    visaDirectDesc: "Use Visa debit card to make instant payments",
    eft: "Bank EFT",
    eftDesc: "Direct bank deposit — arrives in 1-2 business days",
    wise: "Wise",
    wiseDesc: "Pay with bank or card via Wise",
    back: "Back",
    accountType: "Account type",
    personal: "Personal",
    business: "Business",
    phone: "Phone",
    firstName: "First name",
    lastName: "Last name",
    email: "E-mail",
    bank: "Your bank",
    billingAddress: "Billing address",
    line1: "Address line 1",
    line2: "Address line 2",
    city: "City",
    province: "Province/Territory",
    postal: "Postal code",
    country: "Country",
    amountDue: "Amount due",
    pay: (amount: string) => `Pay ${amount}`,
    poweredBy: "Powered by eFinMoney",
    openBank: "Copy payment details",
    openHosted: "Continue",
    pushHint:
      `Send an Interac Autodeposit e-Transfer to ${FINCRA_CAD_INTERAC_ALIAS}. Put the reference in the message field so we can match your deposit.`,
    detailsCopied: "Payment details copied — paste them in your e-Transfer",
    waiting: "Waiting for your Interac e-Transfer…",
    received: "Payment received",
    paymentDetails: "Copy payment details",
    sendTo: "Interac email",
    reference: "Payment code",
    stillNotSent: "Hide payment details",
    showDetails: "Show payment details",
    bankNumber: "Institution (Bank #)",
    transitNumber: "Transit #",
    accountNumber: "Account #",
    eftHint: "Or pay by EFT / bank transfer using these details:",
    flovideWaiting: "Waiting for your Interac e-Transfer…",
    flovidePushHint:
      "Send an Interac Autodeposit e-Transfer to efin@flovide.com. Put the reference in the message field so we can match your deposit.",
    flovideRequestTo: "Send to",
    flovidePoweredBy: "Powered by eFinMoney · Flovide",
    flovideCopyHint: "Autodeposit is on — no security question. Put the reference in the message field.",
    flovideDetailsCopied: "Payment details copied — paste them in your e-Transfer",
    fincraWaiting: "Waiting for your Interac e-Transfer…",
    fincraPushHint:
      `Send an Interac Autodeposit e-Transfer to ${FINCRA_CAD_INTERAC_ALIAS}. Paste the payment code in the message field so Fincra can match your deposit.`,
    interacBankRef: "e-Transfer reference number",
    interacBankRefHint: "From your bank confirmation after you send — for example CAh9ECkx.",
    interacBankRefPlaceholder: "CAh9ECkx",
    interacAmountTransferred: "Amount transferred",
    interacAmountTransferredHint: (amount: string) =>
      `Enter the exact amount you sent. It must match ${amount} or Complete will not go through.`,
    interacAmountTransferredPlaceholder: "0.00",
    interacQty: "Qty",
    interacQtyHint: "Enter 1 — this checkout is one order.",
    interacComplete: "Complete",
  },
  fr: {
    selectMethod: "Choisissez un mode de paiement",
    interac: "Interac",
    interacDesc: "Approuvez un paiement Interac instantané dans votre banque",
    plaid: "TEF bancaire",
    plaidDesc: "Payez par TEF depuis votre banque canadienne liée vers Loop Bank",
    loopBilling: "Lien de paiement Loop",
    loopBillingDesc: "Payer via Loop Billing (TEF · ~4 jours ouvrables)",
    card: "Carte",
    cardDesc: "Utilisez une carte de débit ou de crédit",
    visaDirect: "Visa Direct",
    visaDirectDesc: "Utilisez une carte de débit Visa pour payer instantanément",
    eft: "Virement bancaire (TEF)",
    eftDesc: "Dépôt bancaire direct — 1 à 2 jours ouvrables",
    wise: "Wise",
    wiseDesc: "Payer par virement ou carte via Wise",
    back: "Retour",
    accountType: "Type de compte",
    personal: "Personnel",
    business: "Entreprise",
    phone: "Téléphone",
    firstName: "Prénom",
    lastName: "Nom",
    email: "Courriel",
    bank: "Votre banque",
    billingAddress: "Adresse de facturation",
    line1: "Adresse ligne 1",
    line2: "Adresse ligne 2",
    city: "Ville",
    province: "Province/Territoire",
    postal: "Code postal",
    country: "Pays",
    amountDue: "Montant dû",
    pay: (amount: string) => `Payer ${amount}`,
    poweredBy: "Propulsé par eFinMoney",
    openBank: "Copier les détails",
    openHosted: "Continuer",
    pushHint:
      `Envoyez un Virement Interac Autodeposit à ${FINCRA_CAD_INTERAC_ALIAS}. Mettez la référence dans le message pour que nous puissions apparier le dépôt.`,
    detailsCopied: "Détails copiés — collez-les dans votre Virement Interac",
    waiting: "En attente de votre Virement Interac…",
    received: "Paiement reçu",
    paymentDetails: "Copier les détails",
    sendTo: "Courriel Interac",
    reference: "Code de paiement",
    stillNotSent: "Masquer les détails",
    showDetails: "Afficher les détails",
    bankNumber: "Institution (n° de banque)",
    transitNumber: "N° de transit",
    accountNumber: "N° de compte",
    eftHint: "Ou payez par TEF / virement bancaire :",
    flovideWaiting: "En attente de votre Virement Interac…",
    flovidePushHint:
      "Envoyez un Virement Autodeposit à efin@flovide.com. Mettez la référence dans le message pour que nous puissions apparier le dépôt.",
    flovideRequestTo: "Envoyer à",
    flovidePoweredBy: "Propulsé par eFinMoney · Flovide",
    flovideCopyHint: "Autodeposit activé — aucune question de sécurité. Mettez la référence dans le message.",
    flovideDetailsCopied: "Détails copiés — collez-les dans votre Virement Interac",
    fincraWaiting: "En attente de votre Virement Interac…",
    fincraPushHint:
      `Envoyez un Virement Autodeposit à ${FINCRA_CAD_INTERAC_ALIAS}. Collez le code de paiement dans le message pour que Fincra puisse apparier le dépôt.`,
    interacBankRef: "Numéro de référence Interac",
    interacBankRefHint: "Sur la confirmation de votre banque après l'envoi — par exemple CAh9ECkx.",
    interacBankRefPlaceholder: "CAh9ECkx",
    interacAmountTransferred: "Montant transféré",
    interacAmountTransferredHint: (amount: string) =>
      `Entrez le montant exact envoyé. Il doit correspondre à ${amount}, sinon Terminer sera refusé.`,
    interacAmountTransferredPlaceholder: "0,00",
    interacQty: "Qté",
    interacQtyHint: "Entrez 1 — cette commande est une seule ligne.",
    interacComplete: "Terminer",
  },
} as const;

export const CA_PROVINCES = [
  { code: "AB", name: "Alberta" },
  { code: "BC", name: "British Columbia" },
  { code: "MB", name: "Manitoba" },
  { code: "NB", name: "New Brunswick" },
  { code: "NL", name: "Newfoundland and Labrador" },
  { code: "NS", name: "Nova Scotia" },
  { code: "NT", name: "Northwest Territories" },
  { code: "NU", name: "Nunavut" },
  { code: "ON", name: "Ontario" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "QC", name: "Quebec" },
  { code: "SK", name: "Saskatchewan" },
  { code: "YT", name: "Yukon" },
];

/** Online banking entry points so CAD pay-in can open the sender's bank. */
export const BANK_ETRANSFER_LINKS: Array<{ name: string; url: string }> = [
  { name: "RBC", url: "https://www.rbcroyalbank.com/ways-to-bank/online-banking/index.html" },
  { name: "TD", url: "https://easyweb.td.com/waw/idp/login.htm" },
  { name: "Scotiabank", url: "https://www.scotiaonline.scotiabank.com/online/authentication/authentication.bns" },
  { name: "BMO", url: "https://www1.bmo.com/banking/digital/login" },
  { name: "CIBC", url: "https://www.cibc.com/en/personal-banking/ways-to-bank/online-banking.html" },
  { name: "National Bank", url: "https://www.nbc.ca" },
  { name: "Desjardins", url: "https://accweb.mouv.desjardins.com/identifiantunique/identification" },
  { name: "Tangerine", url: "https://www.tangerine.ca/app/#/login" },
  { name: "Simplii", url: "https://online.simplii.com/ebm-resources/public/client/web/index.html" },
  { name: "EQ Bank", url: "https://secure.eqbank.ca/login" },
];

export function bankLink(bank?: string | null): string | null {
  const name = String(bank || "").trim().toLowerCase();
  if (!name) return null;
  const row = BANK_ETRANSFER_LINKS.find((b) => b.name.toLowerCase() === name);
  return row?.url || null;
}
