/** Local EN/FR strings + Canadian lookups for the Interac checkout only. */

export type Lang = "en" | "fr";

export const CHECKOUT_STRINGS = {
  en: {
    selectMethod: "Select a payment method",
    interac: "Interac",
    interacDesc: "Use bank account to make instant payments",
    card: "Card",
    cardDesc: "Use debit or credit card to make instant payments",
    eft: "Bank EFT",
    eftDesc: "Direct bank deposit — arrives in 1-2 business days",
    back: "Back",
    accountType: "Account type",
    personal: "Personal",
    business: "Business",
    phone: "Phone",
    firstName: "First name",
    lastName: "Last name",
    email: "E-mail",
    bank: "Your bank",
    billingAddress: "Billing address",
    line1: "Address line 1",
    line2: "Address line 2",
    city: "City",
    province: "Province/Territory",
    postal: "Postal code",
    country: "Country",
    amountDue: "Amount due",
    pay: (amount: string) => `Pay ${amount}`,
    poweredBy: "Payments powered by eFinMoney",
    openBank: "Open your banking app",
    detailsCopied: "Payment details copied",
    waiting: "Waiting for your payment…",
    received: "Payment received",
    paymentDetails: "Payment details",
    sendTo: "Send to",
    reference: "Reference",
    stillNotSent: "I haven't paid yet — show me the details again",
  },
  fr: {
    selectMethod: "Choisissez un mode de paiement",
    interac: "Interac",
    interacDesc: "Utilisez votre compte bancaire pour un paiement instantané",
    card: "Carte",
    cardDesc: "Utilisez une carte de débit ou de crédit",
    eft: "Virement bancaire (TEF)",
    eftDesc: "Dépôt bancaire direct — 1 à 2 jours ouvrables",
    back: "Retour",
    accountType: "Type de compte",
    personal: "Personnel",
    business: "Entreprise",
    phone: "Téléphone",
    firstName: "Prénom",
    lastName: "Nom",
    email: "Courriel",
    bank: "Votre banque",
    billingAddress: "Adresse de facturation",
    line1: "Adresse ligne 1",
    line2: "Adresse ligne 2",
    city: "Ville",
    province: "Province/Territoire",
    postal: "Code postal",
    country: "Pays",
    amountDue: "Montant dû",
    pay: (amount: string) => `Payer ${amount}`,
    poweredBy: "Paiements par eFinMoney",
    openBank: "Ouvrir votre application bancaire",
    detailsCopied: "Détails du paiement copiés",
    waiting: "En attente de votre paiement…",
    received: "Paiement reçu",
    paymentDetails: "Détails du paiement",
    sendTo: "Envoyer à",
    reference: "Référence",
    stillNotSent: "Je n'ai pas encore payé — afficher les détails",
  },
} as const;

export const CA_PROVINCES = [
  { code: "AB", name: "Alberta" },
  { code: "BC", name: "British Columbia" },
  { code: "MB", name: "Manitoba" },
  { code: "NB", name: "New Brunswick" },
  { code: "NL", name: "Newfoundland and Labrador" },
  { code: "NS", name: "Nova Scotia" },
  { code: "NT", name: "Northwest Territories" },
  { code: "NU", name: "Nunavut" },
  { code: "ON", name: "Ontario" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "QC", name: "Quebec" },
  { code: "SK", name: "Saskatchewan" },
  { code: "YT", name: "Yukon" },
];

/** e-Transfer entry points for the major Canadian banks, used for the hand-off. */
export const BANK_ETRANSFER_LINKS: Array<{ name: string; url: string }> = [
  { name: "RBC", url: "https://www.rbcroyalbank.com/dig/sign-in.html" },
  { name: "TD", url: "https://authentication.td.com/uap-ui/index.html" },
  { name: "Scotiabank", url: "https://auth.scotiaonline.scotiabank.com/online" },
  { name: "BMO", url: "https://www1.bmo.com/onlinebanking/CI/Login/authentication" },
  { name: "CIBC", url: "https://www.cibconline.cibc.com/ebm-resources/public/banking/cibc/client/web/index.html" },
  { name: "National Bank", url: "https://bao.bnc.ca/auth/login" },
  { name: "Desjardins", url: "https://accesd.desjardins.com/particuliers" },
  { name: "Tangerine", url: "https://www.tangerine.ca/en/log-in" },
  { name: "Simplii", url: "https://online.simplii.com/ebm-resources/public/client/web/index.html" },
  { name: "EQ Bank", url: "https://secure.eqbank.ca/" },
];

export function bankLink(bank?: string | null): string | null {
  if (!bank) return null;
  const needle = bank.trim().toLowerCase();
  return BANK_ETRANSFER_LINKS.find((b) => needle.includes(b.name.toLowerCase()))?.url ?? null;
}
