/** Local EN/FR strings + Canadian lookups for the Interac checkout only. */

import { FINCRA_CAD_INTERAC_ALIAS } from "@/lib/fincraCad";

export type Lang = "en" | "fr";

export const CHECKOUT_STRINGS = {
  en: {
    selectMethod: "Select a payment method",
    interac: "Interac",
    interacDesc: `Send Interac Autodeposit to ${FINCRA_CAD_INTERAC_ALIAS}`,
    plaid: "Interac",
    plaidDesc: `Send Interac Autodeposit to ${FINCRA_CAD_INTERAC_ALIAS}`,
    loopBilling: "Loop payment link",
    loopBillingDesc: "Pay via Loop Billing (EFT bank debit · ~4 business days)",
    card: "Card",
    cardDesc: "Use debit or credit card to make instant payments",
    visaDirect: "Visa Direct",
    visaDirectDesc: "Use Visa debit card to make instant payments",
    eft: "Bank EFT",
    eftDesc: "Direct bank deposit — arrives in 1-2 business days",
    wise: "Wise",
    wiseDesc: "Pay with bank or card via Wise",
    back: "Back",
    accountType: "Account type",
    personal: "Personal",
    business: "Business",
    phone: "Phone",
    firstName: "First name",
    lastName: "Last name",
    email: "E-mail",
    bank: "Your bank",
    billingAddress: "Billing address",
    line1: "Address line 1",
    line2: "Address line 2",
    city: "City",
    province: "Province/Territory",
    postal: "Postal code",
    country: "Country",
    amountDue: "Amount due",
    pay: (amount: string) => `Pay ${amount}`,
    poweredBy: "Powered by eFinMoney",
    openBank: "Copy payment details",
    openHosted: "Continue",
    pushHint:
      `Send an Interac Autodeposit e-Transfer to ${FINCRA_CAD_INTERAC_ALIAS}. Put the reference in the message field so we can match your deposit.`,
    detailsCopied: "Payment details copied — paste them in your e-Transfer",
    waiting: "Waiting for your Interac e-Transfer…",
    received: "Payment received",
    paymentDetails: "Copy payment details",
    sendTo: "Interac email",
    reference: "Payment code",
    stillNotSent: "Hide payment details",
    showDetails: "Show payment details",
    bankNumber: "Institution (Bank #)",
    transitNumber: "Transit #",
    accountNumber: "Account #",
    eftHint: "Or pay by EFT / bank transfer using these details:",
    flovideWaiting: "Waiting for your Interac e-Transfer…",
    flovidePushHint:
      "Send an Interac Autodeposit e-Transfer to efin@flovide.com. Put the reference in the message field so we can match your deposit.",
    flovideRequestTo: "Send to",
    flovidePoweredBy: "Powered by eFinMoney · Flovide",
    flovideCopyHint: "Autodeposit is on — no security question. Put the reference in the message field.",
    flovideDetailsCopied: "Payment details copied — paste them in your e-Transfer",
    fincraWaiting: "Waiting for your Interac e-Transfer…",
    fincraPushHint:
      `Send an Interac Autodeposit e-Transfer to ${FINCRA_CAD_INTERAC_ALIAS}. Paste the payment code in the message field so Fincra can match your deposit.`,
  },
  fr: {
    selectMethod: "Choisissez un mode de paiement",
    interac: "Interac",
    interacDesc: `Envoyez un Virement Autodeposit vers ${FINCRA_CAD_INTERAC_ALIAS}`,
    plaid: "Interac",
    plaidDesc: `Envoyez un Virement Autodeposit vers ${FINCRA_CAD_INTERAC_ALIAS}`,
    loopBilling: "Lien de paiement Loop",
    loopBillingDesc: "Payer via Loop Billing (TEF · ~4 jours ouvrables)",
    card: "Carte",
    cardDesc: "Utilisez une carte de débit ou de crédit",
    visaDirect: "Visa Direct",
    visaDirectDesc: "Utilisez une carte de débit Visa pour payer instantanément",
    eft: "Virement bancaire (TEF)",
    eftDesc: "Dépôt bancaire direct — 1 à 2 jours ouvrables",
    wise: "Wise",
    wiseDesc: "Payer par virement ou carte via Wise",
    back: "Retour",
    accountType: "Type de compte",
    personal: "Personnel",
    business: "Entreprise",
    phone: "Téléphone",
    firstName: "Prénom",
    lastName: "Nom",
    email: "Courriel",
    bank: "Votre banque",
    billingAddress: "Adresse de facturation",
    line1: "Adresse ligne 1",
    line2: "Adresse ligne 2",
    city: "Ville",
    province: "Province/Territoire",
    postal: "Code postal",
    country: "Pays",
    amountDue: "Montant dû",
    pay: (amount: string) => `Payer ${amount}`,
    poweredBy: "Propulsé par eFinMoney",
    openBank: "Copier les détails",
    openHosted: "Continuer",
    pushHint:
      `Envoyez un Virement Interac Autodeposit à ${FINCRA_CAD_INTERAC_ALIAS}. Mettez la référence dans le message pour que nous puissions apparier le dépôt.`,
    detailsCopied: "Détails copiés — collez-les dans votre Virement Interac",
    waiting: "En attente de votre Virement Interac…",
    received: "Paiement reçu",
    paymentDetails: "Copier les détails",
    sendTo: "Courriel Interac",
    reference: "Code de paiement",
    stillNotSent: "Masquer les détails",
    showDetails: "Afficher les détails",
    bankNumber: "Institution (n° de banque)",
    transitNumber: "N° de transit",
    accountNumber: "N° de compte",
    eftHint: "Ou payez par TEF / virement bancaire :",
    flovideWaiting: "En attente de votre Virement Interac…",
    flovidePushHint:
      "Envoyez un Virement Autodeposit à efin@flovide.com. Mettez la référence dans le message pour que nous puissions apparier le dépôt.",
    flovideRequestTo: "Envoyer à",
    flovidePoweredBy: "Propulsé par eFinMoney · Flovide",
    flovideCopyHint: "Autodeposit activé — aucune question de sécurité. Mettez la référence dans le message.",
    flovideDetailsCopied: "Détails copiés — collez-les dans votre Virement Interac",
    fincraWaiting: "En attente de votre Virement Interac…",
    fincraPushHint:
      `Envoyez un Virement Autodeposit à ${FINCRA_CAD_INTERAC_ALIAS}. Collez le code de paiement dans le message pour que Fincra puisse apparier le dépôt.`,
  },
} as const;

export const CA_PROVINCES = [
  { code: "AB", name: "Alberta" },
  { code: "BC", name: "British Columbia" },
  { code: "MB", name: "Manitoba" },
  { code: "NB", name: "New Brunswick" },
  { code: "NL", name: "Newfoundland and Labrador" },
  { code: "NS", name: "Nova Scotia" },
  { code: "NT", name: "Northwest Territories" },
  { code: "NU", name: "Nunavut" },
  { code: "ON", name: "Ontario" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "QC", name: "Quebec" },
  { code: "SK", name: "Saskatchewan" },
  { code: "YT", name: "Yukon" },
];

/**
 * Bank names for the Interac payer form only.
 * We intentionally do NOT deep-link to bank login pages — those URLs 404 or
 * route to "call us" blocks (RBC dig/sign-in, Scotiabank, etc.).
 */
export const BANK_ETRANSFER_LINKS: Array<{ name: string; url: string }> = [
  { name: "RBC", url: "" },
  { name: "TD", url: "" },
  { name: "Scotiabank", url: "" },
  { name: "BMO", url: "" },
  { name: "CIBC", url: "" },
  { name: "National Bank", url: "" },
  { name: "Desjardins", url: "" },
  { name: "Tangerine", url: "" },
  { name: "Simplii", url: "" },
  { name: "EQ Bank", url: "" },
];

/** Always null — bank login deep-links are unreliable; use Plaid or copy details. */
export function bankLink(_bank?: string | null): string | null {
  return null;
}
