-- Insert additional African and international currencies
INSERT INTO currencies (code, name, symbol, flag_emoji, currency_type, decimal_places, is_active) VALUES
-- Major African Currencies
('NGN', 'Nigerian Naira', '₦', '🇳🇬', 'fiat', 2, true),
('GHS', 'Ghanaian Cedi', 'GH₵', '🇬🇭', 'fiat', 2, true),
('ZAR', 'South African Rand', 'R', '🇿🇦', 'fiat', 2, true),
('EGP', 'Egyptian Pound', 'E£', '🇪🇬', 'fiat', 2, true),
('MAD', 'Moroccan Dirham', 'MAD', '🇲🇦', 'fiat', 2, true),
('ETB', 'Ethiopian Birr', 'Br', '🇪🇹', 'fiat', 2, true),
('RWF', 'Rwandan Franc', 'RF', '🇷🇼', 'fiat', 0, true),
('XOF', 'West African CFA Franc', 'CFA', '🌍', 'fiat', 0, true),
('XAF', 'Central African CFA Franc', 'FCFA', '🌍', 'fiat', 0, true),
('MWK', 'Malawian Kwacha', 'MK', '🇲🇼', 'fiat', 2, true),
('BWP', 'Botswana Pula', 'P', '🇧🇼', 'fiat', 2, true),
('MUR', 'Mauritian Rupee', 'Rs', '🇲🇺', 'fiat', 2, true),
('SCR', 'Seychellois Rupee', 'SR', '🇸🇨', 'fiat', 2, true),
('DZD', 'Algerian Dinar', 'DA', '🇩🇿', 'fiat', 2, true),
('TND', 'Tunisian Dinar', 'DT', '🇹🇳', 'fiat', 3, true),
('LYD', 'Libyan Dinar', 'LD', '🇱🇾', 'fiat', 3, true),
('SDG', 'Sudanese Pound', 'SDG', '🇸🇩', 'fiat', 2, true),
('AOA', 'Angolan Kwanza', 'Kz', '🇦🇴', 'fiat', 2, true),
('MZN', 'Mozambican Metical', 'MT', '🇲🇿', 'fiat', 2, true),
('NAD', 'Namibian Dollar', 'N$', '🇳🇦', 'fiat', 2, true),
('SZL', 'Swazi Lilangeni', 'L', '🇸🇿', 'fiat', 2, true),
('LSL', 'Lesotho Loti', 'L', '🇱🇸', 'fiat', 2, true),
('GMD', 'Gambian Dalasi', 'D', '🇬🇲', 'fiat', 2, true),
('SLL', 'Sierra Leonean Leone', 'Le', '🇸🇱', 'fiat', 2, true),
('LRD', 'Liberian Dollar', 'L$', '🇱🇷', 'fiat', 2, true),
('CVE', 'Cape Verdean Escudo', '$', '🇨🇻', 'fiat', 2, true),
('STN', 'São Tomé Dobra', 'Db', '🇸🇹', 'fiat', 2, true),
('KMF', 'Comorian Franc', 'CF', '🇰🇲', 'fiat', 0, true),
('DJF', 'Djiboutian Franc', 'Fdj', '🇩🇯', 'fiat', 0, true),
('ERN', 'Eritrean Nakfa', 'Nfk', '🇪🇷', 'fiat', 2, true),
('SOS', 'Somali Shilling', 'Sh', '🇸🇴', 'fiat', 2, true),
('SSP', 'South Sudanese Pound', 'SSP', '🇸🇸', 'fiat', 2, true),
('MGA', 'Malagasy Ariary', 'Ar', '🇲🇬', 'fiat', 2, true),
('CDF', 'Congolese Franc', 'FC', '🇨🇩', 'fiat', 2, true),
('GNF', 'Guinean Franc', 'FG', '🇬🇳', 'fiat', 0, true),
-- Additional International Currencies
('EUR', 'Euro', '€', '🇪🇺', 'fiat', 2, true),
('GBP', 'British Pound', '£', '🇬🇧', 'fiat', 2, true),
('CHF', 'Swiss Franc', 'CHF', '🇨🇭', 'fiat', 2, true),
('CNY', 'Chinese Yuan', '¥', '🇨🇳', 'fiat', 2, true),
('INR', 'Indian Rupee', '₹', '🇮🇳', 'fiat', 2, true),
('AED', 'UAE Dirham', 'AED', '🇦🇪', 'fiat', 2, true)
ON CONFLICT (code) DO NOTHING;