-- Seed the currencies master with the remaining ISO 4217 currencies offered by
-- the Live FX calculator's picker (src/lib/worldCurrencies.ts) that were not
-- already present. fx_rates.{from,to}_currency FK -> currencies(code), so a
-- currency must exist here before refresh-fx-rates can write a USD->X rate for
-- it and the calculator can quote it. Names come from the picker; symbol
-- defaults to the ISO code (no glyph in the picker source). Idempotent.
INSERT INTO public.currencies (code, name, symbol, currency_type, decimal_places, is_active) VALUES
    ('AFN', 'Afghan Afghani', 'AFN', 'fiat', 2, true),
    ('ALL', 'Albanian Lek', 'ALL', 'fiat', 2, true),
    ('AMD', 'Armenian Dram', 'AMD', 'fiat', 2, true),
    ('ANG', 'Netherlands Antillean Guilder', 'ANG', 'fiat', 2, true),
    ('AWG', 'Aruban Florin', 'AWG', 'fiat', 2, true),
    ('AZN', 'Azerbaijani Manat', 'AZN', 'fiat', 2, true),
    ('BAM', 'Bosnia-Herzegovina Mark', 'BAM', 'fiat', 2, true),
    ('BBD', 'Barbadian Dollar', 'BBD', 'fiat', 2, true),
    ('BGN', 'Bulgarian Lev', 'BGN', 'fiat', 2, true),
    ('BMD', 'Bermudan Dollar', 'BMD', 'fiat', 2, true),
    ('BND', 'Brunei Dollar', 'BND', 'fiat', 2, true),
    ('BOB', 'Bolivian Boliviano', 'BOB', 'fiat', 2, true),
    ('BSD', 'Bahamian Dollar', 'BSD', 'fiat', 2, true),
    ('BTN', 'Bhutanese Ngultrum', 'BTN', 'fiat', 2, true),
    ('BYN', 'Belarusian Ruble', 'BYN', 'fiat', 2, true),
    ('BZD', 'Belize Dollar', 'BZD', 'fiat', 2, true),
    ('CRC', 'Costa Rican Colón', 'CRC', 'fiat', 2, true),
    ('CUP', 'Cuban Peso', 'CUP', 'fiat', 2, true),
    ('CZK', 'Czech Koruna', 'CZK', 'fiat', 2, true),
    ('DOP', 'Dominican Peso', 'DOP', 'fiat', 2, true),
    ('FJD', 'Fijian Dollar', 'FJD', 'fiat', 2, true),
    ('FKP', 'Falkland Islands Pound', 'FKP', 'fiat', 2, true),
    ('GEL', 'Georgian Lari', 'GEL', 'fiat', 2, true),
    ('GIP', 'Gibraltar Pound', 'GIP', 'fiat', 2, true),
    ('GTQ', 'Guatemalan Quetzal', 'GTQ', 'fiat', 2, true),
    ('GYD', 'Guyanaese Dollar', 'GYD', 'fiat', 2, true),
    ('HNL', 'Honduran Lempira', 'HNL', 'fiat', 2, true),
    ('HRK', 'Croatian Kuna', 'HRK', 'fiat', 2, true),
    ('HTG', 'Haitian Gourde', 'HTG', 'fiat', 2, true),
    ('HUF', 'Hungarian Forint', 'HUF', 'fiat', 2, true),
    ('IQD', 'Iraqi Dinar', 'IQD', 'fiat', 2, true),
    ('IRR', 'Iranian Rial', 'IRR', 'fiat', 2, true),
    ('ISK', 'Icelandic Króna', 'ISK', 'fiat', 2, true),
    ('JMD', 'Jamaican Dollar', 'JMD', 'fiat', 2, true),
    ('KGS', 'Kyrgystani Som', 'KGS', 'fiat', 2, true),
    ('KHR', 'Cambodian Riel', 'KHR', 'fiat', 2, true),
    ('KYD', 'Cayman Islands Dollar', 'KYD', 'fiat', 2, true),
    ('KZT', 'Kazakhstani Tenge', 'KZT', 'fiat', 2, true),
    ('LAK', 'Laotian Kip', 'LAK', 'fiat', 2, true),
    ('LBP', 'Lebanese Pound', 'LBP', 'fiat', 2, true),
    ('LKR', 'Sri Lankan Rupee', 'LKR', 'fiat', 2, true),
    ('MDL', 'Moldovan Leu', 'MDL', 'fiat', 2, true),
    ('MKD', 'Macedonian Denar', 'MKD', 'fiat', 2, true),
    ('MMK', 'Myanma Kyat', 'MMK', 'fiat', 2, true),
    ('MNT', 'Mongolian Tugrik', 'MNT', 'fiat', 2, true),
    ('MOP', 'Macanese Pataca', 'MOP', 'fiat', 2, true),
    ('MRU', 'Mauritanian Ouguiya', 'MRU', 'fiat', 2, true),
    ('MVR', 'Maldivian Rufiyaa', 'MVR', 'fiat', 2, true),
    ('NIO', 'Nicaraguan Córdoba', 'NIO', 'fiat', 2, true),
    ('NPR', 'Nepalese Rupee', 'NPR', 'fiat', 2, true),
    ('PAB', 'Panamanian Balboa', 'PAB', 'fiat', 2, true),
    ('PGK', 'Papua New Guinean Kina', 'PGK', 'fiat', 2, true),
    ('PYG', 'Paraguayan Guarani', 'PYG', 'fiat', 2, true),
    ('RON', 'Romanian Leu', 'RON', 'fiat', 2, true),
    ('RSD', 'Serbian Dinar', 'RSD', 'fiat', 2, true),
    ('SBD', 'Solomon Islands Dollar', 'SBD', 'fiat', 2, true),
    ('SHP', 'St. Helena Pound', 'SHP', 'fiat', 2, true),
    ('SLE', 'Sierra Leonean Leone', 'SLE', 'fiat', 2, true),
    ('SRD', 'Surinamese Dollar', 'SRD', 'fiat', 2, true),
    ('SYP', 'Syrian Pound', 'SYP', 'fiat', 2, true),
    ('TJS', 'Tajikistani Somoni', 'TJS', 'fiat', 2, true),
    ('TMT', 'Turkmenistani Manat', 'TMT', 'fiat', 2, true),
    ('TOP', 'Tongan Paʻanga', 'TOP', 'fiat', 2, true),
    ('TTD', 'Trinidad & Tobago Dollar', 'TTD', 'fiat', 2, true),
    ('TWD', 'New Taiwan Dollar', 'TWD', 'fiat', 2, true),
    ('UAH', 'Ukrainian Hryvnia', 'UAH', 'fiat', 2, true),
    ('UYU', 'Uruguayan Peso', 'UYU', 'fiat', 2, true),
    ('UZS', 'Uzbekistan Som', 'UZS', 'fiat', 2, true),
    ('VES', 'Venezuelan Bolívar', 'VES', 'fiat', 2, true),
    ('VUV', 'Vanuatu Vatu', 'VUV', 'fiat', 2, true),
    ('WST', 'Samoan Tala', 'WST', 'fiat', 2, true),
    ('XCD', 'East Caribbean Dollar', 'XCD', 'fiat', 2, true),
    ('XPF', 'CFP Franc', 'XPF', 'fiat', 2, true),
    ('YER', 'Yemeni Rial', 'YER', 'fiat', 2, true),
    ('ZWL', 'Zimbabwean Dollar', 'ZWL', 'fiat', 2, true)
ON CONFLICT (code) DO NOTHING;
